### ISSUE TITLE
Nextep is not compatible with PostgreSQL 9.0+

### ISSUE THREAD

**Issue by christophefondacci** [christophefondacci/nextep-designer#27]
Synchronization breaks because tgisconstraint column was removed in 9.0:
![image](https://cloud.githubusercontent.com/assets/1533154/24840875/0eab6816-1d2b-11e7-9620-8a0cfb3046f5.png)

**Comment by christophefondacci** [comment]
Bruno can you verify? I don't have a PostgreSQL here.

Per https://www.postgresql.org/docs/8.4/static/catalog-pg-trigger.html and https://www.postgresql.org/message-id/CAD3a31X%3DC0hyHuEA67uagGdumm956E8mHmc7LOy4D5JBrn7RRQ%40mail.gmail.com I think it is a reasonable change but I cannot verify it.

**Comment by brunogautier** [comment]
Christophe, the fix is ok. But as it stands, we would no longer be compatible with versions prior to 8.3, since the pg_trigger.tgconstraint column was added in 8.3. So I added a preliminary test to check if the column exists and fallback on pg_trigger.tgisconstraint if not so.
