### ISSUE TITLE
Connection failure to repository database not catched anymore

### ISSUE THREAD

**Issue by brunogautier** [christophefondacci/nextep-designer#30]

**Comment by christophefondacci** [comment]
Can you add a little comment about why you closed it?

**Comment by brunogautier** [comment]
The `IDatabaseConnector` and `IConnectionService` interfaces of the `com.neXtep.designer.installer` plugin were not consistent with the corresponding interfaces of the `com.neXtep.designer.core` plugin in terms of thrown exceptions. So I changed the `IDatabaseConnector` and `IConnectionService` interfaces of the `com.neXtep.designer.installer` plugin to throw `SQLException` exceptions instead of `InstallerException`. Which is besides more logical too.

Connection failure to the repository database is now correctly detected again.
